version: '3'
services:
  api:
    image: akshay090/self-critical.pytorch:api
    # ports: 
      # - "80:80"
  kafka-consumer:
    image: ghcr.io/semantic-search/self-critical-consumer:latest 
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: >
      sh -c "wait-for-it.sh && ./wait-for-it.sh -t 0 api:80 -- python -u main.py"    
    env_file:
      - .env
    depends_on:
      - api
