version: '3'
services:
  api:
    image: akshay090/self-critical.pytorch:api
    # ports: 
      # - "80:80"
  kafka-consumer:
    image: ghcr.io/semantic-search/self-critical-consumer:latest 
    command: python -u main.py
    env_file:
      - .env
    volumes:
      - .:/code
    depends_on:
      - api
